auth-postgres:
  auth:
    postgresPassword: postgres
    database: auth

ingestion-postgres:
  auth:
    postgresPassword: postgres
    database: contacts


authdeployment:
  image: 851725386825.dkr.ecr.us-east-1.amazonaws.com/ms-auth

ingestiondeployment:
  image: 851725386825.dkr.ecr.us-east-1.amazonaws.com/ms-ingestion
