apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: {{.Values.authdeployment.image}}
          ports:
            - containerPort: 5156
          env:
            - name: PORT
              value: '5156'
            - name: MS_URL
              value: "http://ingestion:5155"
            - name: SECRET_KEY
              value: He39zDQW7RdkOcxe3L9qvoSQ/ef40BG6Ro4hrHDjE+U=
            - name: DB_ACCESS
              value: postgres://postgres:postgres@ms-auth-postgres/auth


             
