apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: mouaffak1/ms-ingestion:mouaffak
          ports:
            - containerPort: 5155
          env:
            - name: PORT
              value: '5155'
            - name: SECRET_KEY
              value: He39zDQW7RdkOcxe3L9qvoSQ/ef40BG6Ro4hrHDjE+U=
            - name: DB_ACCESS
              value: postgres://postgres:postgres@ms-ingestion-postgres/contacts
